// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cloudera/terraform-provider-cdp/cdp-sdk-go/gen/cloudprivatelinks/client/operations"
	"github.com/go-openapi/runtime"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCloudPrivateLinksClientService creates a new instance of MockCloudPrivateLinksClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloudPrivateLinksClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloudPrivateLinksClientService {
	mock := &MockCloudPrivateLinksClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCloudPrivateLinksClientService is an autogenerated mock type for the ClientService type
type MockCloudPrivateLinksClientService struct {
	mock.Mock
}

type MockCloudPrivateLinksClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloudPrivateLinksClientService) EXPECT() *MockCloudPrivateLinksClientService_Expecter {
	return &MockCloudPrivateLinksClientService_Expecter{mock: &_m.Mock}
}

// AuthorizePrivateLinkServiceAccess provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) AuthorizePrivateLinkServiceAccess(params *operations.AuthorizePrivateLinkServiceAccessParams, opts ...operations.ClientOption) (*operations.AuthorizePrivateLinkServiceAccessOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizePrivateLinkServiceAccess")
	}

	var r0 *operations.AuthorizePrivateLinkServiceAccessOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*operations.AuthorizePrivateLinkServiceAccessParams, ...operations.ClientOption) (*operations.AuthorizePrivateLinkServiceAccessOK, error)); ok {
		return returnFunc(params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(*operations.AuthorizePrivateLinkServiceAccessParams, ...operations.ClientOption) *operations.AuthorizePrivateLinkServiceAccessOK); ok {
		r0 = returnFunc(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.AuthorizePrivateLinkServiceAccessOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*operations.AuthorizePrivateLinkServiceAccessParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizePrivateLinkServiceAccess'
type MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call struct {
	*mock.Call
}

// AuthorizePrivateLinkServiceAccess is a helper method to define mock.On call
//   - params *operations.AuthorizePrivateLinkServiceAccessParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) AuthorizePrivateLinkServiceAccess(params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call {
	return &MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call{Call: _e.mock.On("AuthorizePrivateLinkServiceAccess",
		append([]interface{}{params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call) Run(run func(params *operations.AuthorizePrivateLinkServiceAccessParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operations.AuthorizePrivateLinkServiceAccessParams
		if args[0] != nil {
			arg0 = args[0].(*operations.AuthorizePrivateLinkServiceAccessParams)
		}
		var arg1 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call) Return(authorizePrivateLinkServiceAccessOK *operations.AuthorizePrivateLinkServiceAccessOK, err error) *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call {
	_c.Call.Return(authorizePrivateLinkServiceAccessOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call) RunAndReturn(run func(params *operations.AuthorizePrivateLinkServiceAccessParams, opts ...operations.ClientOption) (*operations.AuthorizePrivateLinkServiceAccessOK, error)) *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccess_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizePrivateLinkServiceAccessContext provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) AuthorizePrivateLinkServiceAccessContext(ctx context.Context, params *operations.AuthorizePrivateLinkServiceAccessParams, opts ...operations.ClientOption) (*operations.AuthorizePrivateLinkServiceAccessOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizePrivateLinkServiceAccessContext")
	}

	var r0 *operations.AuthorizePrivateLinkServiceAccessOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.AuthorizePrivateLinkServiceAccessParams, ...operations.ClientOption) (*operations.AuthorizePrivateLinkServiceAccessOK, error)); ok {
		return returnFunc(ctx, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.AuthorizePrivateLinkServiceAccessParams, ...operations.ClientOption) *operations.AuthorizePrivateLinkServiceAccessOK); ok {
		r0 = returnFunc(ctx, params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.AuthorizePrivateLinkServiceAccessOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *operations.AuthorizePrivateLinkServiceAccessParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(ctx, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizePrivateLinkServiceAccessContext'
type MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call struct {
	*mock.Call
}

// AuthorizePrivateLinkServiceAccessContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *operations.AuthorizePrivateLinkServiceAccessParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) AuthorizePrivateLinkServiceAccessContext(ctx interface{}, params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call {
	return &MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call{Call: _e.mock.On("AuthorizePrivateLinkServiceAccessContext",
		append([]interface{}{ctx, params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call) Run(run func(ctx context.Context, params *operations.AuthorizePrivateLinkServiceAccessParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *operations.AuthorizePrivateLinkServiceAccessParams
		if args[1] != nil {
			arg1 = args[1].(*operations.AuthorizePrivateLinkServiceAccessParams)
		}
		var arg2 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call) Return(authorizePrivateLinkServiceAccessOK *operations.AuthorizePrivateLinkServiceAccessOK, err error) *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call {
	_c.Call.Return(authorizePrivateLinkServiceAccessOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call) RunAndReturn(run func(ctx context.Context, params *operations.AuthorizePrivateLinkServiceAccessParams, opts ...operations.ClientOption) (*operations.AuthorizePrivateLinkServiceAccessOK, error)) *MockCloudPrivateLinksClientService_AuthorizePrivateLinkServiceAccessContext_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePrivateLinkEndpoint provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) CreatePrivateLinkEndpoint(params *operations.CreatePrivateLinkEndpointParams, opts ...operations.ClientOption) (*operations.CreatePrivateLinkEndpointOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrivateLinkEndpoint")
	}

	var r0 *operations.CreatePrivateLinkEndpointOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*operations.CreatePrivateLinkEndpointParams, ...operations.ClientOption) (*operations.CreatePrivateLinkEndpointOK, error)); ok {
		return returnFunc(params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(*operations.CreatePrivateLinkEndpointParams, ...operations.ClientOption) *operations.CreatePrivateLinkEndpointOK); ok {
		r0 = returnFunc(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreatePrivateLinkEndpointOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*operations.CreatePrivateLinkEndpointParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePrivateLinkEndpoint'
type MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call struct {
	*mock.Call
}

// CreatePrivateLinkEndpoint is a helper method to define mock.On call
//   - params *operations.CreatePrivateLinkEndpointParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) CreatePrivateLinkEndpoint(params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call {
	return &MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call{Call: _e.mock.On("CreatePrivateLinkEndpoint",
		append([]interface{}{params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call) Run(run func(params *operations.CreatePrivateLinkEndpointParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operations.CreatePrivateLinkEndpointParams
		if args[0] != nil {
			arg0 = args[0].(*operations.CreatePrivateLinkEndpointParams)
		}
		var arg1 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call) Return(createPrivateLinkEndpointOK *operations.CreatePrivateLinkEndpointOK, err error) *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call {
	_c.Call.Return(createPrivateLinkEndpointOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call) RunAndReturn(run func(params *operations.CreatePrivateLinkEndpointParams, opts ...operations.ClientOption) (*operations.CreatePrivateLinkEndpointOK, error)) *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePrivateLinkEndpointContext provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) CreatePrivateLinkEndpointContext(ctx context.Context, params *operations.CreatePrivateLinkEndpointParams, opts ...operations.ClientOption) (*operations.CreatePrivateLinkEndpointOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrivateLinkEndpointContext")
	}

	var r0 *operations.CreatePrivateLinkEndpointOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.CreatePrivateLinkEndpointParams, ...operations.ClientOption) (*operations.CreatePrivateLinkEndpointOK, error)); ok {
		return returnFunc(ctx, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.CreatePrivateLinkEndpointParams, ...operations.ClientOption) *operations.CreatePrivateLinkEndpointOK); ok {
		r0 = returnFunc(ctx, params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreatePrivateLinkEndpointOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *operations.CreatePrivateLinkEndpointParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(ctx, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePrivateLinkEndpointContext'
type MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call struct {
	*mock.Call
}

// CreatePrivateLinkEndpointContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *operations.CreatePrivateLinkEndpointParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) CreatePrivateLinkEndpointContext(ctx interface{}, params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call {
	return &MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call{Call: _e.mock.On("CreatePrivateLinkEndpointContext",
		append([]interface{}{ctx, params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call) Run(run func(ctx context.Context, params *operations.CreatePrivateLinkEndpointParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *operations.CreatePrivateLinkEndpointParams
		if args[1] != nil {
			arg1 = args[1].(*operations.CreatePrivateLinkEndpointParams)
		}
		var arg2 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call) Return(createPrivateLinkEndpointOK *operations.CreatePrivateLinkEndpointOK, err error) *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call {
	_c.Call.Return(createPrivateLinkEndpointOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call) RunAndReturn(run func(ctx context.Context, params *operations.CreatePrivateLinkEndpointParams, opts ...operations.ClientOption) (*operations.CreatePrivateLinkEndpointOK, error)) *MockCloudPrivateLinksClientService_CreatePrivateLinkEndpointContext_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePrivateLinkEndpoint provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) DeletePrivateLinkEndpoint(params *operations.DeletePrivateLinkEndpointParams, opts ...operations.ClientOption) (*operations.DeletePrivateLinkEndpointOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeletePrivateLinkEndpoint")
	}

	var r0 *operations.DeletePrivateLinkEndpointOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*operations.DeletePrivateLinkEndpointParams, ...operations.ClientOption) (*operations.DeletePrivateLinkEndpointOK, error)); ok {
		return returnFunc(params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(*operations.DeletePrivateLinkEndpointParams, ...operations.ClientOption) *operations.DeletePrivateLinkEndpointOK); ok {
		r0 = returnFunc(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeletePrivateLinkEndpointOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*operations.DeletePrivateLinkEndpointParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePrivateLinkEndpoint'
type MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call struct {
	*mock.Call
}

// DeletePrivateLinkEndpoint is a helper method to define mock.On call
//   - params *operations.DeletePrivateLinkEndpointParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) DeletePrivateLinkEndpoint(params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call {
	return &MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call{Call: _e.mock.On("DeletePrivateLinkEndpoint",
		append([]interface{}{params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call) Run(run func(params *operations.DeletePrivateLinkEndpointParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operations.DeletePrivateLinkEndpointParams
		if args[0] != nil {
			arg0 = args[0].(*operations.DeletePrivateLinkEndpointParams)
		}
		var arg1 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call) Return(deletePrivateLinkEndpointOK *operations.DeletePrivateLinkEndpointOK, err error) *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call {
	_c.Call.Return(deletePrivateLinkEndpointOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call) RunAndReturn(run func(params *operations.DeletePrivateLinkEndpointParams, opts ...operations.ClientOption) (*operations.DeletePrivateLinkEndpointOK, error)) *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePrivateLinkEndpointContext provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) DeletePrivateLinkEndpointContext(ctx context.Context, params *operations.DeletePrivateLinkEndpointParams, opts ...operations.ClientOption) (*operations.DeletePrivateLinkEndpointOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeletePrivateLinkEndpointContext")
	}

	var r0 *operations.DeletePrivateLinkEndpointOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.DeletePrivateLinkEndpointParams, ...operations.ClientOption) (*operations.DeletePrivateLinkEndpointOK, error)); ok {
		return returnFunc(ctx, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.DeletePrivateLinkEndpointParams, ...operations.ClientOption) *operations.DeletePrivateLinkEndpointOK); ok {
		r0 = returnFunc(ctx, params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeletePrivateLinkEndpointOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *operations.DeletePrivateLinkEndpointParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(ctx, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePrivateLinkEndpointContext'
type MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call struct {
	*mock.Call
}

// DeletePrivateLinkEndpointContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *operations.DeletePrivateLinkEndpointParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) DeletePrivateLinkEndpointContext(ctx interface{}, params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call {
	return &MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call{Call: _e.mock.On("DeletePrivateLinkEndpointContext",
		append([]interface{}{ctx, params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call) Run(run func(ctx context.Context, params *operations.DeletePrivateLinkEndpointParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *operations.DeletePrivateLinkEndpointParams
		if args[1] != nil {
			arg1 = args[1].(*operations.DeletePrivateLinkEndpointParams)
		}
		var arg2 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call) Return(deletePrivateLinkEndpointOK *operations.DeletePrivateLinkEndpointOK, err error) *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call {
	_c.Call.Return(deletePrivateLinkEndpointOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call) RunAndReturn(run func(ctx context.Context, params *operations.DeletePrivateLinkEndpointParams, opts ...operations.ClientOption) (*operations.DeletePrivateLinkEndpointOK, error)) *MockCloudPrivateLinksClientService_DeletePrivateLinkEndpointContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateLinkStatus provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) GetPrivateLinkStatus(params *operations.GetPrivateLinkStatusParams, opts ...operations.ClientOption) (*operations.GetPrivateLinkStatusOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateLinkStatus")
	}

	var r0 *operations.GetPrivateLinkStatusOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*operations.GetPrivateLinkStatusParams, ...operations.ClientOption) (*operations.GetPrivateLinkStatusOK, error)); ok {
		return returnFunc(params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(*operations.GetPrivateLinkStatusParams, ...operations.ClientOption) *operations.GetPrivateLinkStatusOK); ok {
		r0 = returnFunc(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetPrivateLinkStatusOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*operations.GetPrivateLinkStatusParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateLinkStatus'
type MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call struct {
	*mock.Call
}

// GetPrivateLinkStatus is a helper method to define mock.On call
//   - params *operations.GetPrivateLinkStatusParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) GetPrivateLinkStatus(params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call {
	return &MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call{Call: _e.mock.On("GetPrivateLinkStatus",
		append([]interface{}{params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call) Run(run func(params *operations.GetPrivateLinkStatusParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operations.GetPrivateLinkStatusParams
		if args[0] != nil {
			arg0 = args[0].(*operations.GetPrivateLinkStatusParams)
		}
		var arg1 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call) Return(getPrivateLinkStatusOK *operations.GetPrivateLinkStatusOK, err error) *MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call {
	_c.Call.Return(getPrivateLinkStatusOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call) RunAndReturn(run func(params *operations.GetPrivateLinkStatusParams, opts ...operations.ClientOption) (*operations.GetPrivateLinkStatusOK, error)) *MockCloudPrivateLinksClientService_GetPrivateLinkStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateLinkStatusContext provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) GetPrivateLinkStatusContext(ctx context.Context, params *operations.GetPrivateLinkStatusParams, opts ...operations.ClientOption) (*operations.GetPrivateLinkStatusOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateLinkStatusContext")
	}

	var r0 *operations.GetPrivateLinkStatusOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.GetPrivateLinkStatusParams, ...operations.ClientOption) (*operations.GetPrivateLinkStatusOK, error)); ok {
		return returnFunc(ctx, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.GetPrivateLinkStatusParams, ...operations.ClientOption) *operations.GetPrivateLinkStatusOK); ok {
		r0 = returnFunc(ctx, params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetPrivateLinkStatusOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *operations.GetPrivateLinkStatusParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(ctx, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateLinkStatusContext'
type MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call struct {
	*mock.Call
}

// GetPrivateLinkStatusContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *operations.GetPrivateLinkStatusParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) GetPrivateLinkStatusContext(ctx interface{}, params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call {
	return &MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call{Call: _e.mock.On("GetPrivateLinkStatusContext",
		append([]interface{}{ctx, params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call) Run(run func(ctx context.Context, params *operations.GetPrivateLinkStatusParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *operations.GetPrivateLinkStatusParams
		if args[1] != nil {
			arg1 = args[1].(*operations.GetPrivateLinkStatusParams)
		}
		var arg2 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call) Return(getPrivateLinkStatusOK *operations.GetPrivateLinkStatusOK, err error) *MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call {
	_c.Call.Return(getPrivateLinkStatusOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call) RunAndReturn(run func(ctx context.Context, params *operations.GetPrivateLinkStatusParams, opts ...operations.ClientOption) (*operations.GetPrivateLinkStatusOK, error)) *MockCloudPrivateLinksClientService_GetPrivateLinkStatusContext_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrivateLinkEndpointStatuses provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) ListPrivateLinkEndpointStatuses(params *operations.ListPrivateLinkEndpointStatusesParams, opts ...operations.ClientOption) (*operations.ListPrivateLinkEndpointStatusesOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivateLinkEndpointStatuses")
	}

	var r0 *operations.ListPrivateLinkEndpointStatusesOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*operations.ListPrivateLinkEndpointStatusesParams, ...operations.ClientOption) (*operations.ListPrivateLinkEndpointStatusesOK, error)); ok {
		return returnFunc(params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(*operations.ListPrivateLinkEndpointStatusesParams, ...operations.ClientOption) *operations.ListPrivateLinkEndpointStatusesOK); ok {
		r0 = returnFunc(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListPrivateLinkEndpointStatusesOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*operations.ListPrivateLinkEndpointStatusesParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrivateLinkEndpointStatuses'
type MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call struct {
	*mock.Call
}

// ListPrivateLinkEndpointStatuses is a helper method to define mock.On call
//   - params *operations.ListPrivateLinkEndpointStatusesParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) ListPrivateLinkEndpointStatuses(params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call {
	return &MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call{Call: _e.mock.On("ListPrivateLinkEndpointStatuses",
		append([]interface{}{params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call) Run(run func(params *operations.ListPrivateLinkEndpointStatusesParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operations.ListPrivateLinkEndpointStatusesParams
		if args[0] != nil {
			arg0 = args[0].(*operations.ListPrivateLinkEndpointStatusesParams)
		}
		var arg1 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call) Return(listPrivateLinkEndpointStatusesOK *operations.ListPrivateLinkEndpointStatusesOK, err error) *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call {
	_c.Call.Return(listPrivateLinkEndpointStatusesOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call) RunAndReturn(run func(params *operations.ListPrivateLinkEndpointStatusesParams, opts ...operations.ClientOption) (*operations.ListPrivateLinkEndpointStatusesOK, error)) *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrivateLinkEndpointStatusesContext provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) ListPrivateLinkEndpointStatusesContext(ctx context.Context, params *operations.ListPrivateLinkEndpointStatusesParams, opts ...operations.ClientOption) (*operations.ListPrivateLinkEndpointStatusesOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivateLinkEndpointStatusesContext")
	}

	var r0 *operations.ListPrivateLinkEndpointStatusesOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.ListPrivateLinkEndpointStatusesParams, ...operations.ClientOption) (*operations.ListPrivateLinkEndpointStatusesOK, error)); ok {
		return returnFunc(ctx, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.ListPrivateLinkEndpointStatusesParams, ...operations.ClientOption) *operations.ListPrivateLinkEndpointStatusesOK); ok {
		r0 = returnFunc(ctx, params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListPrivateLinkEndpointStatusesOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *operations.ListPrivateLinkEndpointStatusesParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(ctx, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrivateLinkEndpointStatusesContext'
type MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call struct {
	*mock.Call
}

// ListPrivateLinkEndpointStatusesContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *operations.ListPrivateLinkEndpointStatusesParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) ListPrivateLinkEndpointStatusesContext(ctx interface{}, params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call {
	return &MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call{Call: _e.mock.On("ListPrivateLinkEndpointStatusesContext",
		append([]interface{}{ctx, params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call) Run(run func(ctx context.Context, params *operations.ListPrivateLinkEndpointStatusesParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *operations.ListPrivateLinkEndpointStatusesParams
		if args[1] != nil {
			arg1 = args[1].(*operations.ListPrivateLinkEndpointStatusesParams)
		}
		var arg2 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call) Return(listPrivateLinkEndpointStatusesOK *operations.ListPrivateLinkEndpointStatusesOK, err error) *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call {
	_c.Call.Return(listPrivateLinkEndpointStatusesOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call) RunAndReturn(run func(ctx context.Context, params *operations.ListPrivateLinkEndpointStatusesParams, opts ...operations.ClientOption) (*operations.ListPrivateLinkEndpointStatusesOK, error)) *MockCloudPrivateLinksClientService_ListPrivateLinkEndpointStatusesContext_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrivateLinkServicesForRegion provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) ListPrivateLinkServicesForRegion(params *operations.ListPrivateLinkServicesForRegionParams, opts ...operations.ClientOption) (*operations.ListPrivateLinkServicesForRegionOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivateLinkServicesForRegion")
	}

	var r0 *operations.ListPrivateLinkServicesForRegionOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*operations.ListPrivateLinkServicesForRegionParams, ...operations.ClientOption) (*operations.ListPrivateLinkServicesForRegionOK, error)); ok {
		return returnFunc(params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(*operations.ListPrivateLinkServicesForRegionParams, ...operations.ClientOption) *operations.ListPrivateLinkServicesForRegionOK); ok {
		r0 = returnFunc(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListPrivateLinkServicesForRegionOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*operations.ListPrivateLinkServicesForRegionParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrivateLinkServicesForRegion'
type MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call struct {
	*mock.Call
}

// ListPrivateLinkServicesForRegion is a helper method to define mock.On call
//   - params *operations.ListPrivateLinkServicesForRegionParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) ListPrivateLinkServicesForRegion(params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call {
	return &MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call{Call: _e.mock.On("ListPrivateLinkServicesForRegion",
		append([]interface{}{params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call) Run(run func(params *operations.ListPrivateLinkServicesForRegionParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operations.ListPrivateLinkServicesForRegionParams
		if args[0] != nil {
			arg0 = args[0].(*operations.ListPrivateLinkServicesForRegionParams)
		}
		var arg1 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call) Return(listPrivateLinkServicesForRegionOK *operations.ListPrivateLinkServicesForRegionOK, err error) *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call {
	_c.Call.Return(listPrivateLinkServicesForRegionOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call) RunAndReturn(run func(params *operations.ListPrivateLinkServicesForRegionParams, opts ...operations.ClientOption) (*operations.ListPrivateLinkServicesForRegionOK, error)) *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegion_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrivateLinkServicesForRegionContext provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) ListPrivateLinkServicesForRegionContext(ctx context.Context, params *operations.ListPrivateLinkServicesForRegionParams, opts ...operations.ClientOption) (*operations.ListPrivateLinkServicesForRegionOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivateLinkServicesForRegionContext")
	}

	var r0 *operations.ListPrivateLinkServicesForRegionOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.ListPrivateLinkServicesForRegionParams, ...operations.ClientOption) (*operations.ListPrivateLinkServicesForRegionOK, error)); ok {
		return returnFunc(ctx, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.ListPrivateLinkServicesForRegionParams, ...operations.ClientOption) *operations.ListPrivateLinkServicesForRegionOK); ok {
		r0 = returnFunc(ctx, params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListPrivateLinkServicesForRegionOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *operations.ListPrivateLinkServicesForRegionParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(ctx, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrivateLinkServicesForRegionContext'
type MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call struct {
	*mock.Call
}

// ListPrivateLinkServicesForRegionContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *operations.ListPrivateLinkServicesForRegionParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) ListPrivateLinkServicesForRegionContext(ctx interface{}, params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call {
	return &MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call{Call: _e.mock.On("ListPrivateLinkServicesForRegionContext",
		append([]interface{}{ctx, params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call) Run(run func(ctx context.Context, params *operations.ListPrivateLinkServicesForRegionParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *operations.ListPrivateLinkServicesForRegionParams
		if args[1] != nil {
			arg1 = args[1].(*operations.ListPrivateLinkServicesForRegionParams)
		}
		var arg2 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call) Return(listPrivateLinkServicesForRegionOK *operations.ListPrivateLinkServicesForRegionOK, err error) *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call {
	_c.Call.Return(listPrivateLinkServicesForRegionOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call) RunAndReturn(run func(ctx context.Context, params *operations.ListPrivateLinkServicesForRegionParams, opts ...operations.ClientOption) (*operations.ListPrivateLinkServicesForRegionOK, error)) *MockCloudPrivateLinksClientService_ListPrivateLinkServicesForRegionContext_Call {
	_c.Call.Return(run)
	return _c
}

// MigratePrivateLinkEndpoints provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) MigratePrivateLinkEndpoints(params *operations.MigratePrivateLinkEndpointsParams, opts ...operations.ClientOption) (*operations.MigratePrivateLinkEndpointsOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MigratePrivateLinkEndpoints")
	}

	var r0 *operations.MigratePrivateLinkEndpointsOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*operations.MigratePrivateLinkEndpointsParams, ...operations.ClientOption) (*operations.MigratePrivateLinkEndpointsOK, error)); ok {
		return returnFunc(params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(*operations.MigratePrivateLinkEndpointsParams, ...operations.ClientOption) *operations.MigratePrivateLinkEndpointsOK); ok {
		r0 = returnFunc(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.MigratePrivateLinkEndpointsOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*operations.MigratePrivateLinkEndpointsParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigratePrivateLinkEndpoints'
type MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call struct {
	*mock.Call
}

// MigratePrivateLinkEndpoints is a helper method to define mock.On call
//   - params *operations.MigratePrivateLinkEndpointsParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) MigratePrivateLinkEndpoints(params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call {
	return &MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call{Call: _e.mock.On("MigratePrivateLinkEndpoints",
		append([]interface{}{params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call) Run(run func(params *operations.MigratePrivateLinkEndpointsParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operations.MigratePrivateLinkEndpointsParams
		if args[0] != nil {
			arg0 = args[0].(*operations.MigratePrivateLinkEndpointsParams)
		}
		var arg1 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call) Return(migratePrivateLinkEndpointsOK *operations.MigratePrivateLinkEndpointsOK, err error) *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call {
	_c.Call.Return(migratePrivateLinkEndpointsOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call) RunAndReturn(run func(params *operations.MigratePrivateLinkEndpointsParams, opts ...operations.ClientOption) (*operations.MigratePrivateLinkEndpointsOK, error)) *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpoints_Call {
	_c.Call.Return(run)
	return _c
}

// MigratePrivateLinkEndpointsContext provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) MigratePrivateLinkEndpointsContext(ctx context.Context, params *operations.MigratePrivateLinkEndpointsParams, opts ...operations.ClientOption) (*operations.MigratePrivateLinkEndpointsOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MigratePrivateLinkEndpointsContext")
	}

	var r0 *operations.MigratePrivateLinkEndpointsOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.MigratePrivateLinkEndpointsParams, ...operations.ClientOption) (*operations.MigratePrivateLinkEndpointsOK, error)); ok {
		return returnFunc(ctx, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.MigratePrivateLinkEndpointsParams, ...operations.ClientOption) *operations.MigratePrivateLinkEndpointsOK); ok {
		r0 = returnFunc(ctx, params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.MigratePrivateLinkEndpointsOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *operations.MigratePrivateLinkEndpointsParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(ctx, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigratePrivateLinkEndpointsContext'
type MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call struct {
	*mock.Call
}

// MigratePrivateLinkEndpointsContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *operations.MigratePrivateLinkEndpointsParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) MigratePrivateLinkEndpointsContext(ctx interface{}, params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call {
	return &MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call{Call: _e.mock.On("MigratePrivateLinkEndpointsContext",
		append([]interface{}{ctx, params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call) Run(run func(ctx context.Context, params *operations.MigratePrivateLinkEndpointsParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *operations.MigratePrivateLinkEndpointsParams
		if args[1] != nil {
			arg1 = args[1].(*operations.MigratePrivateLinkEndpointsParams)
		}
		var arg2 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call) Return(migratePrivateLinkEndpointsOK *operations.MigratePrivateLinkEndpointsOK, err error) *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call {
	_c.Call.Return(migratePrivateLinkEndpointsOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call) RunAndReturn(run func(ctx context.Context, params *operations.MigratePrivateLinkEndpointsParams, opts ...operations.ClientOption) (*operations.MigratePrivateLinkEndpointsOK, error)) *MockCloudPrivateLinksClientService_MigratePrivateLinkEndpointsContext_Call {
	_c.Call.Return(run)
	return _c
}

// RevokePrivateLinkServiceAccess provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) RevokePrivateLinkServiceAccess(params *operations.RevokePrivateLinkServiceAccessParams, opts ...operations.ClientOption) (*operations.RevokePrivateLinkServiceAccessOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RevokePrivateLinkServiceAccess")
	}

	var r0 *operations.RevokePrivateLinkServiceAccessOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*operations.RevokePrivateLinkServiceAccessParams, ...operations.ClientOption) (*operations.RevokePrivateLinkServiceAccessOK, error)); ok {
		return returnFunc(params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(*operations.RevokePrivateLinkServiceAccessParams, ...operations.ClientOption) *operations.RevokePrivateLinkServiceAccessOK); ok {
		r0 = returnFunc(params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.RevokePrivateLinkServiceAccessOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*operations.RevokePrivateLinkServiceAccessParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokePrivateLinkServiceAccess'
type MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call struct {
	*mock.Call
}

// RevokePrivateLinkServiceAccess is a helper method to define mock.On call
//   - params *operations.RevokePrivateLinkServiceAccessParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) RevokePrivateLinkServiceAccess(params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call {
	return &MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call{Call: _e.mock.On("RevokePrivateLinkServiceAccess",
		append([]interface{}{params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call) Run(run func(params *operations.RevokePrivateLinkServiceAccessParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operations.RevokePrivateLinkServiceAccessParams
		if args[0] != nil {
			arg0 = args[0].(*operations.RevokePrivateLinkServiceAccessParams)
		}
		var arg1 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call) Return(revokePrivateLinkServiceAccessOK *operations.RevokePrivateLinkServiceAccessOK, err error) *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call {
	_c.Call.Return(revokePrivateLinkServiceAccessOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call) RunAndReturn(run func(params *operations.RevokePrivateLinkServiceAccessParams, opts ...operations.ClientOption) (*operations.RevokePrivateLinkServiceAccessOK, error)) *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccess_Call {
	_c.Call.Return(run)
	return _c
}

// RevokePrivateLinkServiceAccessContext provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) RevokePrivateLinkServiceAccessContext(ctx context.Context, params *operations.RevokePrivateLinkServiceAccessParams, opts ...operations.ClientOption) (*operations.RevokePrivateLinkServiceAccessOK, error) {
	// operations.ClientOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RevokePrivateLinkServiceAccessContext")
	}

	var r0 *operations.RevokePrivateLinkServiceAccessOK
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.RevokePrivateLinkServiceAccessParams, ...operations.ClientOption) (*operations.RevokePrivateLinkServiceAccessOK, error)); ok {
		return returnFunc(ctx, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *operations.RevokePrivateLinkServiceAccessParams, ...operations.ClientOption) *operations.RevokePrivateLinkServiceAccessOK); ok {
		r0 = returnFunc(ctx, params, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.RevokePrivateLinkServiceAccessOK)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *operations.RevokePrivateLinkServiceAccessParams, ...operations.ClientOption) error); ok {
		r1 = returnFunc(ctx, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokePrivateLinkServiceAccessContext'
type MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call struct {
	*mock.Call
}

// RevokePrivateLinkServiceAccessContext is a helper method to define mock.On call
//   - ctx context.Context
//   - params *operations.RevokePrivateLinkServiceAccessParams
//   - opts ...operations.ClientOption
func (_e *MockCloudPrivateLinksClientService_Expecter) RevokePrivateLinkServiceAccessContext(ctx interface{}, params interface{}, opts ...interface{}) *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call {
	return &MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call{Call: _e.mock.On("RevokePrivateLinkServiceAccessContext",
		append([]interface{}{ctx, params}, opts...)...)}
}

func (_c *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call) Run(run func(ctx context.Context, params *operations.RevokePrivateLinkServiceAccessParams, opts ...operations.ClientOption)) *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *operations.RevokePrivateLinkServiceAccessParams
		if args[1] != nil {
			arg1 = args[1].(*operations.RevokePrivateLinkServiceAccessParams)
		}
		var arg2 []operations.ClientOption
		variadicArgs := make([]operations.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(operations.ClientOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call) Return(revokePrivateLinkServiceAccessOK *operations.RevokePrivateLinkServiceAccessOK, err error) *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call {
	_c.Call.Return(revokePrivateLinkServiceAccessOK, err)
	return _c
}

func (_c *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call) RunAndReturn(run func(ctx context.Context, params *operations.RevokePrivateLinkServiceAccessParams, opts ...operations.ClientOption) (*operations.RevokePrivateLinkServiceAccessOK, error)) *MockCloudPrivateLinksClientService_RevokePrivateLinkServiceAccessContext_Call {
	_c.Call.Return(run)
	return _c
}

// SetTransport provides a mock function for the type MockCloudPrivateLinksClientService
func (_mock *MockCloudPrivateLinksClientService) SetTransport(transport runtime.ContextualTransport) {
	_mock.Called(transport)
	return
}

// MockCloudPrivateLinksClientService_SetTransport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTransport'
type MockCloudPrivateLinksClientService_SetTransport_Call struct {
	*mock.Call
}

// SetTransport is a helper method to define mock.On call
//   - transport runtime.ContextualTransport
func (_e *MockCloudPrivateLinksClientService_Expecter) SetTransport(transport interface{}) *MockCloudPrivateLinksClientService_SetTransport_Call {
	return &MockCloudPrivateLinksClientService_SetTransport_Call{Call: _e.mock.On("SetTransport", transport)}
}

func (_c *MockCloudPrivateLinksClientService_SetTransport_Call) Run(run func(transport runtime.ContextualTransport)) *MockCloudPrivateLinksClientService_SetTransport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 runtime.ContextualTransport
		if args[0] != nil {
			arg0 = args[0].(runtime.ContextualTransport)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCloudPrivateLinksClientService_SetTransport_Call) Return() *MockCloudPrivateLinksClientService_SetTransport_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCloudPrivateLinksClientService_SetTransport_Call) RunAndReturn(run func(transport runtime.ContextualTransport)) *MockCloudPrivateLinksClientService_SetTransport_Call {
	_c.Run(run)
	return _c
}
