// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AcceptTermsRequest Request object for an accept terms request.
//
// swagger:model AcceptTermsRequest
type AcceptTermsRequest struct {

	// The name of the terms to accept.
	// Required: true
	TermsName *string `json:"termsName"`
}

// Validate validates this accept terms request
func (m *AcceptTermsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTermsName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AcceptTermsRequest) validateTermsName(formats strfmt.Registry) error {

	if err := validate.Required("termsName", "body", m.TermsName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AcceptTermsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AcceptTermsRequest) UnmarshalBinary(b []byte) error {
	var res AcceptTermsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
