// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// AddMachineUserToGroupResponse Response object for add machine user to group request.
//
// swagger:model AddMachineUserToGroupResponse
type AddMachineUserToGroupResponse interface{}
