// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DescribeSSHPublicKeyRequest Request object for describe SSH public key.
//
// swagger:model DescribeSshPublicKeyRequest
type DescribeSSHPublicKeyRequest struct {

	// The CRN of the user or machine user that the SSH public key belongs to. If it is not included, it defaults to the actor making the request.
	ActorCrn string `json:"actorCrn,omitempty"`

	// The SSH public key CRN or its SHA256 fingerprint.
	// Required: true
	CrnOrFingerprint *string `json:"crnOrFingerprint"`
}

// Validate validates this describe Ssh public key request
func (m *DescribeSSHPublicKeyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCrnOrFingerprint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribeSSHPublicKeyRequest) validateCrnOrFingerprint(formats strfmt.Registry) error {

	if err := validate.Required("crnOrFingerprint", "body", m.CrnOrFingerprint); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DescribeSSHPublicKeyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DescribeSSHPublicKeyRequest) UnmarshalBinary(b []byte) error {
	var res DescribeSSHPublicKeyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
