// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListSSHPublicKeysRequest Request object for list SSH public key.
//
// swagger:model ListSshPublicKeysRequest
type ListSSHPublicKeysRequest struct {

	// The CRN of the user or machine user to list SSH public keys for. If it is not included, it defaults to the actor making the request.
	ActorCrn string `json:"actorCrn,omitempty"`
}

// Validate validates this list Ssh public keys request
func (m *ListSSHPublicKeysRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListSSHPublicKeysRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListSSHPublicKeysRequest) UnmarshalBinary(b []byte) error {
	var res ListSSHPublicKeysRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
