// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListTermsResponse Response object for a list terms response.
//
// swagger:model ListTermsResponse
type ListTermsResponse struct {

	// The token to use when requesting the next set of results. If not present, there are no additional results.
	NextToken string `json:"nextToken,omitempty"`

	// The terms.
	// Required: true
	TermsAcceptanceStates []*TermsSummary `json:"termsAcceptanceStates"`
}

// Validate validates this list terms response
func (m *ListTermsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTermsAcceptanceStates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListTermsResponse) validateTermsAcceptanceStates(formats strfmt.Registry) error {

	if err := validate.Required("termsAcceptanceStates", "body", m.TermsAcceptanceStates); err != nil {
		return err
	}

	for i := 0; i < len(m.TermsAcceptanceStates); i++ {
		if swag.IsZero(m.TermsAcceptanceStates[i]) { // not required
			continue
		}

		if m.TermsAcceptanceStates[i] != nil {
			if err := m.TermsAcceptanceStates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("termsAcceptanceStates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListTermsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListTermsResponse) UnmarshalBinary(b []byte) error {
	var res ListTermsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
