// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UnassignMachineUserResourceRoleRequest Request object for an unassign machine user role request.
//
// swagger:model UnassignMachineUserResourceRoleRequest
type UnassignMachineUserResourceRoleRequest struct {

	// The machine user to unassign the resource role from.
	// Required: true
	MachineUserName *string `json:"machineUserName"`

	// The CRN of the resource for which the resource role rights will be unassigned.
	// Required: true
	ResourceCrn *string `json:"resourceCrn"`

	// The CRN of the resource role to unassigned from the machine user.
	// Required: true
	ResourceRoleCrn *string `json:"resourceRoleCrn"`
}

// Validate validates this unassign machine user resource role request
func (m *UnassignMachineUserResourceRoleRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMachineUserName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceCrn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceRoleCrn(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnassignMachineUserResourceRoleRequest) validateMachineUserName(formats strfmt.Registry) error {

	if err := validate.Required("machineUserName", "body", m.MachineUserName); err != nil {
		return err
	}

	return nil
}

func (m *UnassignMachineUserResourceRoleRequest) validateResourceCrn(formats strfmt.Registry) error {

	if err := validate.Required("resourceCrn", "body", m.ResourceCrn); err != nil {
		return err
	}

	return nil
}

func (m *UnassignMachineUserResourceRoleRequest) validateResourceRoleCrn(formats strfmt.Registry) error {

	if err := validate.Required("resourceRoleCrn", "body", m.ResourceRoleCrn); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnassignMachineUserResourceRoleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnassignMachineUserResourceRoleRequest) UnmarshalBinary(b []byte) error {
	var res UnassignMachineUserResourceRoleRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
