// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UnassignUserRoleRequest Request object for an unassign user role request.
//
// swagger:model UnassignUserRoleRequest
type UnassignUserRoleRequest struct {

	// The role to unassigned from the user. Can be the role's CRN or name.
	// Required: true
	Role *string `json:"role"`

	// The user to unassigned the roles from. Can be the user CRN or id.
	// Required: true
	User *string `json:"user"`
}

// Validate validates this unassign user role request
func (m *UnassignUserRoleRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnassignUserRoleRequest) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	return nil
}

func (m *UnassignUserRoleRequest) validateUser(formats strfmt.Registry) error {

	if err := validate.Required("user", "body", m.User); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnassignUserRoleRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnassignUserRoleRequest) UnmarshalBinary(b []byte) error {
	var res UnassignUserRoleRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
